// Vendored from Yoga.Net (MIT, see LICENSE in this folder), a C# port of Meta's Yoga 3.2.1.
#nullable enable
#pragma warning disable
using System;
using System.Collections;
using System.Collections.Generic;
// Copyright (c) Meta Platforms, Inc. and affiliates.
//
// This source code is licensed under the MIT license found in the
// LICENSE file in the root directory of this source tree.

// @generated by enums.py

namespace ScriptedScreensHtml.Yoga
{
    public enum Dimension : byte
    {
        Width = 0,
        Height = 1,
    }

    public static class DimensionExtensions
    {
        public const int OrdinalCount = 2;

        public static string ToString(Dimension dimension)
        {
            return dimension switch
            {
                Dimension.Width => "width",
                Dimension.Height => "height",
                _ => "unknown"
            };
        }
    }
}

