// Vendored from Yoga.Net (MIT, see LICENSE in this folder), a C# port of Meta's Yoga 3.2.1.
#nullable enable
#pragma warning disable
using System;
using System.Collections;
using System.Collections.Generic;
// Copyright (c) Meta Platforms, Inc. and affiliates.
//
// This source code is licensed under the MIT license found in the
// LICENSE file in the root directory of this source tree.

// @generated by enums.py

namespace ScriptedScreensHtml.Yoga;

public enum Wrap : byte
{
    NoWrap = 0,
    Wrap = 1,
    WrapReverse = 2,
}

public static class WrapExtensions
{
    public const int OrdinalCount = 3;

    public static string ToDebugString(this Wrap e)
    {
        return e switch
        {
            Wrap.NoWrap => "NoWrap",
            Wrap.Wrap => "Wrap",
            Wrap.WrapReverse => "WrapReverse",
            _ => throw new ArgumentOutOfRangeException(nameof(e), e, "Invalid Wrap value")
        };
    }
}

